[package]
name = "primitives"
version = "0.1.0"
edition = "2024"
authors = ["lodineD"]
default-run = "arrays"


[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "operators"
path = "src/operators.rs"

[[bin]]
name = "tuples"
path = "src/tuples.rs"

[[bin]]
name = "arrays"
path = "src/arrays.rs"

[dependencies]
