[package]
name = "custome_types"
version = "0.1.0"
edition = "2024"
authors = ["lodineD"]
default-run = "Enums_linked-list"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "structures"
path = "src/structures.rs"

[[bin]]
name = "ownership"
path = "src/ownership.rs"

[[bin]]
name = "Enums"
path = "src/Enums.rs"

[[bin]]
name = "Enums_use"
path = "src/Enums_use.rs"

[[bin]]
name = "Enums_Clike"
path = "src/Enums_Clike.rs"

[[bin]]
name = "Enums_linked-list"
path = "src/Enums_linked-list.rs"

[[bin]]
name = "constants"
path = "src/constants.rs"

[dependencies]
